export const imgAssets = {
    error: require('../../assets/img/error-icon.png'),
    play: require('../../assets/img/play.png'),
    pause: require('../../assets/img/pause.png'),
    rewind: require('../../assets/img/rewind.png'),
    fforward: require('../../assets/img/fast-forward.png'),
    skipPrev: require('../../assets/img/skip-prev.png'),
    skipNext: require('../../assets/img/skip-next.png'),
    notFound: require('../../assets/img/not-found.png'),
    back: require('../../assets/img/back.png'),
    fullscreen: require('../../assets/img/fullscreen.png'),
    download: require('../../assets/img/download.png'),
    downloadRound: require('../../assets/img/download-round.png'),
    close: require('../../assets/img/close.png'),
    homeFill: require('../../assets/img/home-fill.png'),
    homeLine: require('../../assets/img/home-line.png'),
    libraryFill: require('../../assets/img/library-fill.png'),
    libraryLine: require('../../assets/img/library-line.png'),
    ok: require('../../assets/img/ok.png'),
    edit: require('../../assets/img/edit.png'),
    checked: require('../../assets/img/checked.png'),
    delete: require('../../assets/img/delete.png'),
    nothing: require('../../assets/img/nothing.png'),
} as const